### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by pdas9647** [Widle-Studio/Grocery-App#12]
![Screenshot_1678851361](https://user-images.githubusercontent.com/74731500/225199853-782393f8-3e2d-409b-9611-901043f380db.png)

**Comment by widlestudiollp** [comment]
Hello @pdas9647 feel free to solve it and submit PR for the same

**Comment by pdas9647** [comment]
Hey, I tried to run your app. But the phone no field is not a textfield,
instead just a text, so don't understand what do you want to do? Btw I have
resolved the overflow issue, but since I don't understand your moto I
didn't submit PR

**Comment by widlestudiollp** [comment]
Thank you for the quick response as you submit the code others can use your solved issue this is why we open source the code so, like you are trying and using.

**Comment by Rizwan201** [comment]
@widlestudiollp is this issue of overflow resolved if not can u assign me this?

**Comment by pdas9647** [comment]
I don't think I can assign, the repo owner only can do that

**Comment by widlestudiollp** [comment]
> @widlestudiollp is this issue of overflow resolved if not can u assign me this?

Feel free to generate the Pull Request(PR) with your changes. 

**PR format**
- What are you changing 
- Why are you making these changes

**Comment by Rizwan201** [comment]
@widlestudiollp Issue resolved PR raised pls check

**Comment by widlestudiollp** [comment]
https://github.com/Widle-Studio/Grocery-App/pull/13
